# Loading data into Pandas

In [2]:
import pandas as pd
import numpy as np

In [10]:
#reading from a csv file
poke = pd.read_csv('pokemon.csv')
print(poke)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

# Reading data in Pandas

In [20]:
# Read Headers
print(poke.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [21]:
# Read each column
print(poke.Name[0:5])

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [28]:
# Reading each row
print(poke.iloc[0:4])

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False

In [26]:
# To read a specific location
print(poke.iloc[2,1])

Venusaur

In [31]:
# for running conditions

poke.loc[poke['Type 1'] == 'Fire']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# Sorting/Describing Data

In [34]:
#all stats for the columns
poke.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [39]:
#to sort the table based on one factor
poke.sort_values('Name',ascending =1)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [41]:
#To sort based on multiple factors
poke.sort_values(['Type 1','HP'],ascending =[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

# Making changes to data

In [43]:
poke.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [72]:
# To make a total of all powers
#poke['Total'] = poke['HP'] + poke['Attack']+poke['Defense'] + poke['Sp. Atk'] + poke['Sp. Def']+ poke['Speed']
poke.head(5)

# better method
poke['Total'] = poke.iloc[:,4:10].sum(axis = 1)
poke.head(5)

,#,Name,Type 1,Type 2,Sp. Def,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk
0,1,Bulbasaur,Grass,Poison,65,45,1,False,1239.0,45,49,49,65
1,2,Ivysaur,Grass,Poison,80,60,1,False,1585.0,60,62,63,80
2,3,Venusaur,Grass,Poison,100,80,1,False,2065.0,80,82,83,100
3,3,VenusaurMega Venusaur,Grass,Poison,120,80,1,False,2441.0,80,100,123,122
4,4,Charmander,Fire,NaN,50,65,1,False,1194.0,39,52,43,60

In [63]:
#to delete a column

#poke = poke.drop(columns = ['Total'])
#poke.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [71]:
# Shifting a column to another place

poke['Total'] = poke.iloc[:,4:10].sum(axis = 1)

cols = list(poke.columns)
poke = poke[cols[0:4] + [cols[-1]] + cols[4:-1]]

poke.head(5)

,#,Name,Type 1,Type 2,Sp. Def,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk
0,1,Bulbasaur,Grass,Poison,65,45,1,False,1083.0,45,49,49,65
1,2,Ivysaur,Grass,Poison,80,60,1,False,1384.0,60,62,63,80
2,3,Venusaur,Grass,Poison,100,80,1,False,1804.0,80,82,83,100
3,3,VenusaurMega Venusaur,Grass,Poison,120,80,1,False,2160.0,80,100,123,122
4,4,Charmander,Fire,NaN,50,65,1,False,1039.0,39,52,43,60

# Saving modified file

In [75]:
poke.to_csv('modified.csv')

In [78]:
poke.to_excel('modified1.xlsx',index =False)

# Filtering Data

In [85]:
#Bool
#in pandas we use & instead of and

new_x = poke.loc[(poke['Type 1'] == 'Grass') & (poke['Type 2'] == 'Poison')]

new_x.to_csv('filtered.csv')

new_x

,#,Name,Type 1,Type 2,Sp. Def,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk
0,1,Bulbasaur,Grass,Poison,65,45,1,False,1239.0,45,49,49,65
1,2,Ivysaur,Grass,Poison,80,60,1,False,1585.0,60,62,63,80
2,3,Venusaur,Grass,Poison,100,80,1,False,2065.0,80,82,83,100
3,3,VenusaurMega Venusaur,Grass,Poison,120,80,1,False,2441.0,80,100,123,122
48,43,Oddish,Grass,Poison,65,30,1,False,1253.0,45,50,55,75
49,44,Gloom,Grass,Poison,75,40,1,False,1568.0,60,65,70,85
50,45,Vileplume,Grass,Poison,90,50,1,False,1943.0,75,80,85,110
75,69,Bellsprout,Grass,Poison,30,40,1,False,1238.0,50,75,35,70
76,70,Weepinbell,Grass,Poison,45,55,1,False,1598.0,65,90,50,85
77,71,Victreebel,Grass,Poison,70,70,1,False,1988.0,80,105,65,100
344,315,Roselia,Grass,Poison,80,65,3,False,1524.0,50,60,45,100
451,406,Budew,Grass,Poison,70,55,4,False,1067.0,40,30,35,50
452,407,Roserade,Grass,Poison,105,90,4,False,1942.0,60,70,65,125
651,590,Foongus,Grass,Poison,55,15,5,False,1259.0,69,55,45,55
652,591,Amoonguss,Grass,Poison,80,30,5,False,1989.0,114,85,70,85

In [86]:
# to get new indexes for our new table

new_x.reset_index(drop = True,inplace = True)

print(new_x)

      #                   Name Type 1  Type 2  Sp. Def  Speed  Generation  \
0     1              Bulbasaur  Grass  Poison       65     45           1
1     2                Ivysaur  Grass  Poison       80     60           1
2     3               Venusaur  Grass  Poison      100     80           1
3     3  VenusaurMega Venusaur  Grass  Poison      120     80           1
4    43                 Oddish  Grass  Poison       65     30           1
5    44                  Gloom  Grass  Poison       75     40           1
6    45              Vileplume  Grass  Poison       90     50           1
7    69             Bellsprout  Grass  Poison       30     40           1
8    70             Weepinbell  Grass  Poison       45     55           1
9    71             Victreebel  Grass  Poison       70     70           1
10  315                Roselia  Grass  Poison       80     65           3
11  406                  Budew  Grass  Poison       70     55           4
12  407               Roserade  Grass  Poison      105     90           4
13  590                Foongus  Grass  Poison       55     15           5
14  591              Amoonguss  Grass  Poison       80     30           5

    Legendary   Total   HP  Attack  Defense  Sp. Atk
0       False  1239.0   45      49       49       65
1       False  1585.0   60      62       63       80
2       False  2065.0   80      82       83      100
3       False  2441.0   80     100      123      122
4       False  1253.0   45      50       55       75
5       False  1568.0   60      65       70       85
6       False  1943.0   75      80       85      110
7       False  1238.0   50      75       35       70
8       False  1598.0   65      90       50       85
9       False  1988.0   80     105       65      100
10      False  1524.0   50      60       45      100
11      False  1067.0   40      30       35       50
12      False  1942.0   60      70       65      125
13      False  1259.0   69      55       45       55
14      False  1989.0  114      85       70       85

# Aggregate Statistics(groupby)

In [89]:
#mean
poke.groupby(['Type 1']).mean().sort_values('Total',ascending = 0)

,#,Sp. Def,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk
Type 1,,,,,,,,,,
Dragon,474.375000,88.843750,83.031250,3.875000,0.375000,2225.281250,83.312500,112.125000,86.375000,96.843750
Steel,442.851852,80.629630,55.259259,3.851852,0.148148,1982.703704,65.222222,92.703704,126.370370,67.518519
Flying,677.750000,72.500000,102.500000,5.500000,0.500000,1909.500000,70.750000,78.750000,66.250000,94.250000
Psychic,380.807018,86.280702,81.491228,3.385965,0.245614,1861.473684,70.631579,71.456140,67.684211,98.403509
Rock,392.727273,75.477273,55.909091,3.454545,0.090909,1854.590909,65.363636,92.863636,100.795455,63.340909
Fire,327.403846,72.211538,74.442308,3.211538,0.096154,1831.269231,69.903846,84.769231,67.769231,88.980769
Ground,356.281250,62.750000,63.906250,3.156250,0.125000,1820.156250,73.781250,95.750000,84.843750,56.468750
Dark,461.354839,69.516129,76.161290,4.032258,0.064516,1797.000000,66.806452,88.387097,70.225806,74.645161
Ghost,486.500000,76.468750,64.343750,4.187500,0.062500,1753.562500,64.437500,73.781250,81.187500,79.343750
Ice,423.541667,76.291667,63.458333,3.541667,0.083333,1744.250000,72.000000,72.750000,71.416667,77.541667
Water,303.089286,70.517857,65.964286,2.857143,0.035714,1737.517857,72.062500,74.151786,72.946429,74.812500
Fighting,363.851852,64.703704,66.074074,3.370370,0.000000,1728.481481,69.851852,96.777778,65.925926,53.111111
Electric,363.500000,73.704545,84.500000,3.272727,0.090909,1724.272727,59.795455,69.090909,66.295455,90.022727
Grass,344.871429,70.428571,61.928571,3.357143,0.042857,1692.714286,67.271429,73.214286,70.800000,77.500000
Fairy,449.529412,84.705882,48.588235,4.117647,0.058824,1663.235294,74.117647,61.529412,65.705882,78.529412
Normal,319.173469,63.724490,71.551020,3.051020,0.020408,1652.897959,77.275510,73.469388,59.846939,55.816327
Poison,251.785714,64.392857,63.571429,2.535714,0.000000,1624.964286,67.250000,74.678571,68.821429,60.428571
Bug,334.492754,64.797101,61.681159,3.217391,0.000000,1529.753623,56.884058,70.971014,70.724638,53.869565

In [92]:
#count like this
poke.groupby(['Type 1']).count()

#or

poke['count'] = 1

print(poke.groupby(['Type 1']).count()['count'])

poke = poke.drop(columns = ['count'])

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64